{% set name = "hyperbox-brain" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UTS-CASLab/hyperbox-brain/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 12979e9b7be4d0d82da7cbc71cc4e6c87eef8a33516b20f6a1064903f7aae987

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - matplotlib
    - joblib
  run:
    - python >=3.6

test:
  imports:
    - hbbrain
    - hbbrain.tests
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://uts-caslab.github.io/hyperbox-brain/
  summary: 'A scikit-learn compatible hyperbox-based machine learning library in Python'
  description: |
    hyperbox-brain is a Python open source toolbox implementing hyperbox-based machine learning algorithms
    built on top of scikit-learn and is distributed under the GPL-3.0 license. The project was started in
    2018 by Prof. Bogdan Gabrys and Dr. Thanh Tung Khuat at the Complex Adaptive Systems Lab - The University 
    of Technology Sydney. This project is a core module aiming to the formulation of explainable lifelong 
    learning systems in near future.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://hyperbox-brain.readthedocs.io/en/latest/
  dev_url: https://github.com/UTS-CASLab/hyperbox-brain

extra:
  recipe-maintainers:
    - thanhtung09t2
